
with open('kiểm thử\maze_map1.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xxx xxxxxxxxxxxxxxxxxx\n')
  outfile.write('xxx  xx     xxxxxxxxxx\n')
  outfile.write('x x xxxxx  xxxx xxx xx\n')
  outfile.write('xxx xxxxxxxx   xxxx  x\n')
  outfile.write('x          xxxxxx  x x\n')
  outfile.write('xxxxxxx x      xx  x x\n') 
  outfile.write('xxxxxxxxxxxxxx  xx   x\n')
  outfile.write('x          x xxSx x  x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open('kiểm thử\maze_map2.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('        xx xx        x\n')
  outfile.write('x   x x     xxxxxxxxxx\n')
  outfile.write('x x x xxx  xxxx xxx xx\n')
  outfile.write('x x x x xxxx   xxxx  x\n')
  outfile.write('x          xx xxx  x x\n')
  outfile.write('xxxxxxx x      xx  x x\n') 
  outfile.write('xxxxxxxxxxxx x  xx   x\n')
  outfile.write('x          x xx xxx  x\n')
  outfile.write('xxxxx x  x x x    Sx x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open('kiểm thử\maze_map3.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x   xx xx        x\n')
  outfile.write('x   x x     xxxxxxxxxx\n')
  outfile.write('x x x xxx  xxxx xxx xx\n')
  outfile.write('  x x x x xx   xxxx  x\n')
  outfile.write('x          xx xxx  x x\n')
  outfile.write('xxxxxxx x      xx  x x\n') 
  outfile.write('xxxxxxxxx  x x  xx   x\n')
  outfile.write('x          x   S  x  x\n')
  outfile.write('xxxxx x  x x xx    x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open('kiểm thử\maze_map4.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x   xx xx         \n')
  outfile.write('x   x x     xxx xxx xx\n')
  outfile.write('x x x xxx  xxxx x   xx\n')
  outfile.write('x x x x x xx      x  x\n')
  outfile.write('x          xx xxx  x x\n')
  outfile.write('xxxxxxx x      xx  x x\n') 
  outfile.write('xxxxxxxxx  xxx  xxx  x\n')
  outfile.write('xS         x x xx x  x\n')
  outfile.write('xxxxx x  x x x     x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open ('kiểm thử\maze_map5.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x x x x x xx   xxxxxx   xxx    xxxx\n')
  outfile.write('xx   xx               xx xxx  xxxxx\n')
  outfile.write('xx xxx  xxxxxx xxx xx xx xxx xxxxxx\n')
  outfile.write('xxx xx x  xxxx xx  xx xx xxx xxxxxx\n')
  outfile.write('xxx x xx    xx x xx   xx xx       x\n')
  outfile.write('xxx     xxx xx   xx xxx xxx xxxxx x\n')
  outfile.write('xxxx  xx xx xxx xxx xxx xxx xxxxx  \n')
  outfile.write('xx xx  xxx   xx xxx          xxx  x\n')
  outfile.write('xx  xx x  xx x      xx xx xx xxx xx\n')
  outfile.write('xx xxx xx xx x  xxxxxx xx xx     xx\n')
  outfile.write('xx     xxx x xx x  x   xx xx xxx xx\n')
  outfile.write('xx xxxxxxx xxxx   xxxx xx xx xxx xx\n')
  outfile.write('xx  x  x x xxx Sx xxxx          xxx\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
  
with open('kiểm thử\maze_map6p.txt', 'w') as outfile:
  outfile.write('2\n')
  outfile.write('3 6 -3\n')
  outfile.write('6 7 -1\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x   xx xx        x\n')
  outfile.write('x   x x     xxxxxxxxxx\n')
  outfile.write('x x x +xx  xxxx xxx xx\n')
  outfile.write('  x x x x xx   xxxx  x\n')
  outfile.write('x          xx xxx  x x\n')
  outfile.write('xxxxxxx+x      xx  x x\n') 
  outfile.write('xxxxxxxxx  x x  xx   x\n')
  outfile.write('x          x x Sx x  x\n')
  outfile.write('xxxxx x  x x x     x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

with open('kiểm thử\maze_map7p.txt', 'w') as outfile:
  outfile.write('3\n')
  outfile.write('6 7 -1\n')
  outfile.write('1 7 -2\n')
  outfile.write('7 15 -4\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x  +xx xx         \n')
  outfile.write('x   x x     xxx xxx xx\n')
  outfile.write('x x x xxx  xxxx x   xx\n')
  outfile.write('x x x x x xx      x  x\n')
  outfile.write('x          xx xxx  x x\n')
  outfile.write('xxxxxxx+x      xx  x x\n') 
  outfile.write('xxxxxxxxx  xxx +xxx  x\n')
  outfile.write('xS         x x xx x  x\n')
  outfile.write('xxxxx x  x x x     x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

